name: Commit Time Gist Report

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # every Sunday

jobs:
  commit-time-gist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Get Commit Times
        run: |
          git log --pretty=format:"%an %aI" > commits.txt

          python3 <<EOF > report.md
import datetime

with open('commits.txt') as f:
    times = [line.strip().split()[-1] for line in f.readlines()]

counts = {"🌞 Morning": 0, "🌆 Daytime": 0, "🌃 Evening": 0, "🌙 Night": 0}
total = len(times)

for t in times:
    hour = datetime.datetime.fromisoformat(t).hour
    if 5 <= hour < 12:
        counts["🌞 Morning"] += 1
    elif 12 <= hour < 17:
        counts["🌆 Daytime"] += 1
    elif 17 <= hour < 21:
        counts["🌃 Evening"] += 1
    else:
        counts["🌙 Night"] += 1

def bar(percent):
    full = int(percent // 4)
    return '█' * full + '░' * (25 - full)

print("## ⏰ Commit Time Distribution\\n")
for label, count in counts.items():
    pct = (count / total) * 100
    print(f"{label:<13} {count:3} commits  {bar(pct)}  {pct:.1f}%")
EOF

      - name: Create or Update Gist
        uses: andymckay/gh-gist@v1
        with:
          token: Gists
          gist_id: https://gist.github.com/yashvisharma1204/3c520cc86a0d6fe81a30017559d198ed
          file_name: Contribution.md
          file_path: report.md
