name: Default metrics

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.plugin.default.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata

      - name: Upload metrics
        uses: actions/upload-artifact@v3
        with:
          name: metrics
          path: assets/metrics.plugin.default.svg
