name: Update gist with top leetcode skills

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'

      - name: Install compatible dependencies
        run: |
          pip install --upgrade pip
          pip uninstall -y numpy pandas || true
          pip install numpy==1.24.4 pandas==1.5.3
          pip install -r requirements.txt

      - name: Update gist
        run: python main.py
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          LEETCODE_USERNAME: ${{ secrets.LEETCODE_USERNAME }}
