name: Update gist with top leetcode skills
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: update gist
        run: python main.py
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          LEETCODE_USERNAME: ${{ secrets.LEETCODE_USERNAME }}
          IGNORED_SKILLS: ${{ vars.IGNORED_SKILLS }}
          HIDE_DIFFICULTY: ${{ vars.HIDE_DIFFICULTY }}
