name: Update Contributions in Gist

on:
  schedule:
    - cron: "0 0 * * 1"   # Runs every Monday at midnight
  workflow_dispatch:      # Allows manual trigger 

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Pull Requests
        run: |
          curl -s -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/search/issues?q=author:yashvisharma1204+type:pr+is:public" \
          | jq '.items[] | "- [" + .title + "](" + .html_url + ") - " + .repository_url' \
          > contributions.md

      - name: Update Gist
        uses: andymckay/gist-update-action@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          gist_id: 02f2962ebc64e93068507b372db61fa3
          file_name: contributions.md
