name: Zen Garden

on:
  schedule:
    - cron: '0 5 * * 0'  # Every Sunday
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Generate Zen Garden
        run: |
          pip install --quiet requests
          python generate_zen_garden.py

      - name: Replace Zen Garden in README
        run: |
          content=$(cat zen_garden.txt)
          awk '/<!--START:ZEN_GARDEN-->/ { print; found=1; next }
               /<!--END:ZEN_GARDEN-->/ { found=0 } !found' README.md > temp.md
          echo "$content" >> temp.md
          echo "<!--END:ZEN_GARDEN-->" >> temp.md
          mv temp.md README.md

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md zen_garden.txt
          git commit -m "🌿 Update Zen Garden"
          git push
