name: Update Word Cloud

on:
  schedule:
    - cron: '0 0 * * 0' # every Sunday
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: pip install wordcloud matplotlib

      - name: Generate Word Cloud
        run: python generate_wordcloud.py

      - name: Commit & Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add wordcloud.png README.md
          git commit -m "Update word cloud"
          git push
